version: 2.1
        orbs:
        cypress: cypress-io/cypress@3
        workflows:
        build:
        jobs:
        - cypress/run:
        name: Chrome
        cypress-command: 'npx cypress run --record --parallel --group chrome --browser chrome'
        start-command: 'npm start'
        parallelism: 4
        install-browsers: true
        - cypress/run:
        name: Firefox
        cypress-command:
        'npx cypress run --record --parallel --group firefox --browser
        firefox --spec
        C:\Users\azouaghi\Documents\CypressProjects\CypressCucumberPMO\cypress\e2e\Utilities\actions.cy.js'
        start-command: 'npm start'
        parallelism: 2
        install-browsers: true
